version: "3"
services:
  app:
    image: hapi
    ports: 
      - "3000:3000"
    depends_on:
      - mongodb
      - redisdb
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: "27017"
      REDIS_HOST: redisdb
      REDIS_PORT: "6379"
  micro:
    image: beequeue-micro
    depends_on:
      - mongodb
      - redisdb
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: "27017"
      REDIS_HOST: redisdb
      REDIS_PORT: "6379"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  redisdb:
    image: redis
    ports:
      - "6379:6379"