version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      MONGO_USER: reddituser
      MONGO_PASS: redditpass
      MONGO_DB: reddit-demo
    networks:
      - reddit
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongodb:/data/mongodb
  redisdb:
    image: redis
    volumes:
      - redis:/data/
    ports:
      - "6379"
    networks:
      - reddit
  app:
    image: hapi-backend
    ports: 
      - "3000:3000"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: "27017"
      MONGO_DB: reddit-demo
      MONGO_USER: reddituser
      MONGO_PASS: redditpass
      REDIS_HOST: redisdb
      REDIS_PORT: "6379"
    networks:
      - reddit
  micro:
    image: beequeue-micro
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: "27017"
      MONGO_DB: reddit-demo
      MONGO_USER: reddituser
      MONGO_PASS: redditpass
      REDIS_HOST: redisdb
      REDIS_PORT: "6379"
    networks:
      - reddit
volumes:
  mongodb:
  redis:
networks:
  reddit: